# Site settings
title: 重生云
author: Chopin
description: "在碧蓝中肆意遨游,缕缕阳光也为你闪耀."
encoding: utf-8
markdown: kramdown
baseurl: 
# Menu
menu:
  - menu.md
  - about.md
# Contact Icons
contact:
  - link: mailto:asdfqwerzxcv51@163.com
    icon: fa-envelope-o
  - link: https://github.com/xiaochopin
    icon: fa-github
#  - link: 
#    icon: fa-twitter
# GitHub Repo for your site
issue_report:
  github: xiaochopin/xiaochopin.github.io
# Google Analytics
#google_analytics: 
# Disqus
disqus:
  shortname: xiaochopin
# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - jekyll-crisp-minimal-theme.gemspec
