# Site settings
title: 重生云
author: Chopin
description: "在天空上,自由飞翔,朵朵白云都为你护航.在碧蓝中肆意遨游,缕缕阳光也为你闪耀."
encoding: utf-8
markdown: kramdown
baseurl: /
# Menu
menu:
  - menu.md
  - about.md
# Contact Icons
contact:
  - link: /feed.xml
    icon: fa-file-code-o  
  - link: mailto:xiaochopin@foxmail.com
    icon: fa-envelope-o
  - link: https://github.com/xiaochopin
    icon: fa-github
# GitHub Repo for your site
issue_report:
  github: xiaochopin/xiaochopin.github.io
# Exclusion
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
